micronaut:
  server:
    port: 8080
  application:
    name: chatgpt
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

netty:
  default:
    allocator:
      max-order: 3

chat-gpt:
  secret-key: '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'
  chat:
    url: 'https://api.openai.com/v1/chat/completions'
    model: 'gpt-3.5-turbo'